name: quickfire
description: A powerful flutter CLI tool to speed up your development cycle with BLoC Feature drive approach, authentication, database, onboarding, UI components and Payments.
version: 1.0.1
repository: https://github.com/FOSS-Community/quickfire

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  quickfire: quickfire
