name: quickfire
description: A powerful flutter CLI tool to generate bloc based feature driven development.
version: 1.0.0
repository: https://github.com/FOSS-Community/quickfire

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  quickfire: quickfire
