name: quickfire
description: auth, Bloc, onboarding, Payment, UI and Play Store deployment, effortlessly woven for an elevated development experience.
version: 1.0.5
repository: https://github.com/FOSS-Community/quickfire

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  http: ^1.1.2
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  quickfire: quickfire
